# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LearningService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15LearningService.proto\x12\x08learning\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x12LearningModelNames\x12\r\n\x05names\x18\x01 \x03(\t\"7\n\rTrainedModels\x12&\n\x06models\x18\x01 \x03(\x0b\x32\x16.learning.TrainedModel\"\xb5\x01\n\x0cTrainedModel\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12:\n\nstatistics\x18\x04 \x03(\x0b\x32&.learning.TrainedModel.StatisticsEntry\x1a\x31\n\x0fStatisticsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"f\n\x05Model\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x33\n\x10model_parameters\x18\x03 \x01(\x0b\x32\x19.learning.ModelParameters\"\x91\x01\n\x0fModelParameters\x12\x1a\n\x12time_series_length\x18\x01 \x01(\x05\x12/\n\x0e\x63ut_parameters\x18\x02 \x01(\x0e\x32\x17.learning.CutParameters\x12\x31\n\x0f\x66ill_parameters\x18\x03 \x01(\x0e\x32\x18.learning.FillParameters\"6\n\rTrainResponse\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.learning.TrainStatus*S\n\x0e\x46illParameters\x12\x14\n\x10\x46ILL_ZEROES_BOTH\x10\x00\x12\x14\n\x10\x46ILL_ZEROES_LEFT\x10\x01\x12\x15\n\x11\x46ILL_ZEROES_RIGHT\x10\x02*:\n\rCutParameters\x12\x0c\n\x08\x43UT_LEFT\x10\x00\x12\r\n\tCUT_RIGHT\x10\x01\x12\x0c\n\x08\x43UT_BOTH\x10\x02*%\n\x0bTrainStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\xde\x01\n\x0fLearningService\x12N\n\x16GetLearningModelsNames\x12\x16.google.protobuf.Empty\x1a\x1c.learning.LearningModelNames\x12\x43\n\x10GetTrainedModels\x12\x16.google.protobuf.Empty\x1a\x17.learning.TrainedModels\x12\x36\n\nTrainModel\x12\x0f.learning.Model\x1a\x17.learning.TrainResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LearningService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAINEDMODEL_STATISTICSENTRY._options = None
  _TRAINEDMODEL_STATISTICSENTRY._serialized_options = b'8\001'
  _FILLPARAMETERS._serialized_start=650
  _FILLPARAMETERS._serialized_end=733
  _CUTPARAMETERS._serialized_start=735
  _CUTPARAMETERS._serialized_end=793
  _TRAINSTATUS._serialized_start=795
  _TRAINSTATUS._serialized_end=832
  _LEARNINGMODELNAMES._serialized_start=64
  _LEARNINGMODELNAMES._serialized_end=99
  _TRAINEDMODELS._serialized_start=101
  _TRAINEDMODELS._serialized_end=156
  _TRAINEDMODEL._serialized_start=159
  _TRAINEDMODEL._serialized_end=340
  _TRAINEDMODEL_STATISTICSENTRY._serialized_start=291
  _TRAINEDMODEL_STATISTICSENTRY._serialized_end=340
  _MODEL._serialized_start=342
  _MODEL._serialized_end=444
  _MODELPARAMETERS._serialized_start=447
  _MODELPARAMETERS._serialized_end=592
  _TRAINRESPONSE._serialized_start=594
  _TRAINRESPONSE._serialized_end=648
  _LEARNINGSERVICE._serialized_start=835
  _LEARNINGSERVICE._serialized_end=1057
# @@protoc_insertion_point(module_scope)
