# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ModelsService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ModelsService.proto\x12\x06models\"\x15\n\x05Model\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"&\n\x04\x46ile\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ile_ext\x18\x02 \x01(\t\"R\n\x16ModelPredictionRequest\x12\x1a\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x0c.models.File\x12\x1c\n\x05model\x18\x02 \x01(\x0b\x32\r.models.Model\"0\n\x17ModelPredictionResponse\x12\x15\n\rclassified_as\x18\x01 \x01(\t2\xc3\x01\n\rModelsService\x12U\n\x12GetModelPrediction\x12\x1e.models.ModelPredictionRequest\x1a\x1f.models.ModelPredictionResponse\x12[\n\x14GetModelsPredictions\x12\x1e.models.ModelPredictionRequest\x1a\x1f.models.ModelPredictionResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ModelsService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEL._serialized_start=31
  _MODEL._serialized_end=52
  _FILE._serialized_start=54
  _FILE._serialized_end=92
  _MODELPREDICTIONREQUEST._serialized_start=94
  _MODELPREDICTIONREQUEST._serialized_end=176
  _MODELPREDICTIONRESPONSE._serialized_start=178
  _MODELPREDICTIONRESPONSE._serialized_end=226
  _MODELSSERVICE._serialized_start=229
  _MODELSSERVICE._serialized_end=424
# @@protoc_insertion_point(module_scope)
