# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendingService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14SendingService.proto\x12\x07sending\"C\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.sending.SendingStatus\"/\n\x0b\x42\x61tchedFile\x12\x12\n\nfile_batch\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t*\"\n\rSendingStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32G\n\x0eSendingService\x12\x35\n\x08SendFile\x12\x14.sending.BatchedFile\x1a\x11.sending.Response(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SendingService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDINGSTATUS._serialized_start=151
  _SENDINGSTATUS._serialized_end=185
  _RESPONSE._serialized_start=33
  _RESPONSE._serialized_end=100
  _BATCHEDFILE._serialized_start=102
  _BATCHEDFILE._serialized_end=149
  _SENDINGSERVICE._serialized_start=187
  _SENDINGSERVICE._serialized_end=258
# @@protoc_insertion_point(module_scope)
